### ISSUE TITLE
Navbar Update

### ISSUE THREAD

**Issue by EAdornado** [mgguild/ai-games#79]
Make navbar extend end to end
![image](https://github.com/user-attachments/assets/c1d13b94-14e2-4043-8275-f327665861b9)

**Comment by dev0614** [comment]
Hello, team.

Can I get involved in your team?
Will update this issue.

**Comment by dev0614** [comment]
I created new pr.
I added `unoptimized` property to all images tag and sharp package to project.
Pls check it.

**Comment by dev0614** [comment]
could you let me know the reason to close the pr?

**Comment by EAdornado** [comment]
Hello @dev0614 , are you employed at MGG? we are not aware of a new Developer. I closed your PR since you are not from our company.

**Comment by dev0614** [comment]
Sorry.

I want to get involved in your team.
I mentioned this at the first of this conversation. I want to have a meeting with you.

Thank you.
